Repository AY2324S2-CS2113-T11-3/tp, pull requests merged in 2024-03, with the labels that each got.

#26 Add `occasion` command
  src/main/java/florizz/command/ListOccasionCommand.java
  src/main/java/florizz/core/Florizz.java
  src/main/java/florizz/core/FlowerDictionary.java
  src/main/java/florizz/core/OccasionDictionary.java
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/core/Ui.java
Labels: type.Enhancement

#38 Add flowers
  src/main/java/florizz/command/AddFlowerCommand.java
  src/main/java/florizz/command/RemoveFlowerCommand.java
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/core/Ui.java
  src/main/java/florizz/objects/Bouquet.java
  src/main/java/florizz/objects/Flower.java
Labels: priority.High, severity.High

#40 Added more texts to the help command
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/core/Ui.java
Labels: priority.Medium

#42 Updated UserGuide.md
  docs/UserGuide.md
  src/main/java/florizz/core/Parser.java
Labels: priority.Low

#65 Add price information
  FlorizzLogger.xml
  src/main/java/florizz/core/FlowerDictionary.java
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/core/Ui.java
  src/main/java/florizz/objects/Flower.java
  src/test/java/florizz/objects/FlowerTest.java
Labels: priority.Medium

#68 Debugged Total Estimated Price, converted price from Int to Double, and added more JavaDoc comments
  FlorizzLogger.xml
  src/main/java/florizz/core/FlowerDictionary.java
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/core/Ui.java
  src/main/java/florizz/objects/Flower.java
  src/test/java/florizz/objects/FlowerTest.java
Labels: priority.Medium, severity.Low

#71 Fuzzy logic
  FlorizzLogger.xml
  src/main/java/florizz/core/FuzzyLogic.java
  src/main/java/florizz/core/Parser.java
Labels: type.Epic, priority.Medium

#76 RemoveFlowerCommand, HelpCommand, ListOccasionCommand UML
  FlorizzLogger.xml
  FlorizzLogger.xml.lck
  docs/UML-diagrams/Jeffinson/Jeffinson-UML-Help.png
  docs/UML-diagrams/Jeffinson/Jeffinson-UML-Help.puml
  docs/UML-diagrams/Jeffinson/Jeffinson-UML-Remove.png
  docs/UML-diagrams/Jeffinson/Jeffinson-UML-Remove.puml
  docs/UML-diagrams/Jeffinson/Jeffinson-style.puml
  src/main/java/florizz/core/FlowerDictionary.java
  src/main/java/florizz/core/FuzzyLogic.java
  src/main/java/florizz/objects/Flower.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium

#83 Fuzzy logic
  src/main/java/florizz/core/Parser.java
Labels: type.Bug

#84 Add more valid items to Fuzzy Logic
  src/main/java/florizz/core/FuzzyLogic.java
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/core/Ui.java
Labels: type.Enhancement, priority.Medium
