Repository AY2324S2-CS2113-T11-3/tp, pull requests merged in 2024-04, with the labels that each got.

#87 Add Damerau-Levenshtein distance and fixed a bug on parser
  src/main/java/florizz/core/FuzzyLogic.java
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/core/Ui.java
Labels: type.Bug, priority.High, severity.High

#88 Fix a bug on parser
  src/main/java/florizz/core/Parser.java
Labels: type.Bug, severity.Low

#89 Refactored and updated Info Command to support flowers with different meanings for different colours
  src/main/java/florizz/command/InfoCommand.java
  src/main/java/florizz/core/FlowerDictionary.java
  src/main/java/florizz/core/Ui.java
  src/main/java/florizz/objects/Flower.java
Labels: type.Enhancement, priority.Medium

#99 Updated flowers and info command in UserGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#106 Update userguide for fuzzy logic
  docs/UserGuide.md
  src/main/java/florizz/core/Ui.java
Labels: priority.High

#110 Fix bug 0x quantity flower
  src/main/java/florizz/objects/Bouquet.java
Labels: severity.Low

#113 Changed Ui for recommend to remove redundancy and grammar errors
  docs/UserGuide.md
  src/main/java/florizz/core/Ui.java
Labels: priority.Medium, severity.Low

#153 PE-D review fixing
  docs/UserGuide.md
  src/main/java/florizz/core/FlowerDictionary.java
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/core/Ui.java
  src/main/java/florizz/objects/Bouquet.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.High, severity.Medium

#156 Adding Colour Selection to add and remove flowers
  src/main/java/florizz/command/AddFlowerCommand.java
  src/main/java/florizz/command/RemoveFlowerCommand.java
  src/main/java/florizz/core/FlowerDictionary.java
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/core/Ui.java
  src/main/java/florizz/objects/Bouquet.java
  src/main/java/florizz/objects/Flower.java
  src/main/java/florizz/storage/Storage.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, priority.Medium

#158 Fixed PE-D bugs
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/objects/Flower.java
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, severity.Medium

#162 Fuzzy Logic enhancement
  src/main/java/florizz/command/RecommendCommand.java
  src/main/java/florizz/core/FuzzyLogic.java
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/core/Ui.java
Labels: type.Enhancement, priority.Medium

#166 PE-D bug fixes
  src/main/java/florizz/command/RecommendCommand.java
  src/main/java/florizz/core/Florizz.java
  src/main/java/florizz/core/FlorizzException.java
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/objects/Bouquet.java
Labels: type.Bug, priority.High, severity.Medium

#168 Jeffinson's PPP
  docs/team/JeffinsonDarmawan.md
  src/main/java/florizz/core/Ui.java
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#169 Bug fixes
  docs/UML-diagrams/Ian/(old)InfoCommandUML.png
  docs/UML-diagrams/Ian/InfoCommandUML.png
  docs/UML-diagrams/Ian/InfoCommandUML.puml
  docs/UML-diagrams/Ijaaz/(old)Ijaaz-UML.png
  docs/UML-diagrams/Ijaaz/Ijaaz-UML.png
  docs/UML-diagrams/Ijaaz/Ijaaz-UML.puml
  docs/team/IanFH.md
  docs/team/Ijaaz01.md
Labels: priority.High

#173 Table format
  build.gradle
  docs/UserGuide.md
  docs/team/jeffinsondarmawan.md
  src/main/java/florizz/command/CompareCommand.java
  src/main/java/florizz/command/InfoCommand.java
  src/main/java/florizz/core/FlowerDictionary.java
  src/main/java/florizz/core/FuzzyLogic.java
  src/main/java/florizz/core/Parser.java
  src/main/java/florizz/core/Ui.java
  src/main/java/florizz/objects/Flower.java
  src/main/java/florizz/objects/TableData.java
  src/test/java/florizz/command/CompareCommandTest.java
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, priority.Medium

#180 Compare-DG
  docs/DeveloperGuide.md
  docs/UML-diagrams/Jeffinson/Jeffinson-UML-compare.png
  docs/UML-diagrams/Jeffinson/Jeffinson-UML-compare.puml
  src/test/java/florizz/command/CompareCommandTest.java
Labels: type.Story, priority.Medium
